# Generated by Django 5.2.7 on 2025-11-14 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_doctor__1e9ac0_idx'),
        ('chat_room', '0002_remove_chatroom_disease_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at'], name='chat_room_c_updated_715450_idx'),
        ),
    ]
