services:
  db:
    image: postgres:15
    container_name: vitasys-db
    restart: always
    environment:
      POSTGRES_DB: vitasysdata
      POSTGRES_USER: vitasysadmin
      POSTGRES_PASSWORD: vitasys2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vitasysadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: vitasys-redis
    command: ["redis-server"]
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitasys-web
    command: >
      sh -c "
        while ! nc -z db 5432; do sleep 1; done &&
        uv run python manage.py migrate &&
        uv run python manage.py collectstatic --noinput &&
        uv run daphne -b 0.0.0.0 -p 8000 Vitasys.asgi:application
      "
    volumes:
      - .:/app
      - static_volume:/app/Vitasys/static
      - media_volume:/app/Vitasys/media
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitasys-celery
    command: sh -c "sleep 15 && uv run celery -A Vitasys worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - web
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitasys-celery-beat
    command: sh -c "sleep 20 && uv run celery -A Vitasys beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: