# Generated by Django 5.2.7 on 2025-11-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authapi', '0003_doctor_unique_doctor_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Authapi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='Authapi.patient')),
            ],
            options={
                'verbose_name': 'Doctor Review',
                'verbose_name_plural': 'Doctor Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', '-created_at'], name='doctor_dash_doctor__730f6d_idx'), models.Index(fields=['rating'], name='doctor_dash_rating_d1ee01_idx')],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
