# Generated by Django 5.2.7 on 2025-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapi', '0003_doctor_unique_doctor_phone_and_more'),
        ('appointments', '0002_remove_appointment_appointment_appoint_5be6a4_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status', 'appointment_date'], name='appointment_doctor__1e9ac0_idx'),
        ),
    ]
