# Generated by Django 6.0.2 on 2026-02-22 08:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('superadmin', 'Super Admin')], max_length=15, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('otp_type', models.CharField(blank=True, help_text="'verification' during signup | 'reset' after forgot-password | ", max_length=15, null=True)),
                ('otp_send_count', models.IntegerField(default=0, help_text='OTP emails sent this session. Hard cap: 5.')),
                ('login_attempts', models.IntegerField(default=0)),
                ('login_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Medical Council Registration Number', max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before doctor can access clinical features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, help_text='e.g. B.Sc Nursing, GNM, Post Basic B.Sc', max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_insurance', models.BooleanField(default=False)),
                ('ins_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('known_allergies', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('chronic_diseases', models.TextField(blank=True, help_text='Comma-separated list', null=True)),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(blank=True, help_text='Pharmacy Council Registration / License Number', max_length=50, null=True, unique=True)),
                ('qualification', models.CharField(blank=True, help_text='e.g. B.Pharm, M.Pharm, D.Pharm', max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacist',
                'verbose_name_plural': 'Pharmacists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_custo_role_6a37b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='users_custo_is_veri_8bba47_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_profile_complete'], name='users_custo_is_prof_acefbb_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['user'], name='users_docto_user_id_1e9ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['phone_number'], name='users_docto_phone_n_da4f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_approved'], name='users_docto_is_appr_e9d9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['city'], name='users_docto_city_b7c36e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='users_docto_special_f28b5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_doctor_phone'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['user'], name='users_nurse_user_id_8788ef_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['phone_number'], name='users_nurse_phone_n_558fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['department'], name='users_nurse_departm_f1b364_idx'),
        ),
        migrations.AddIndex(
            model_name='nurse',
            index=models.Index(fields=['is_approved'], name='users_nurse_is_appr_b99c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='nurse',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_nurse_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user'], name='users_patie_user_id_5efe82_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='users_patie_phone_n_e68942_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['city'], name='users_patie_city_eeeaa5_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['user'], name='users_pharm_user_id_26a72c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['phone_number'], name='users_pharm_phone_n_0c3328_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['license_number'], name='users_pharm_license_d2219d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['is_approved'], name='users_pharm_is_appr_ec417c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacist',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_pharmacist_phone'),
        ),
    ]
