# Generated by Django 5.2.7 on 2025-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapi', '0002_alter_customuser_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_doctor_phone'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_patient_phone'),
        ),
    ]
